
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MyckiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.product_images: /uploads/images/blog
    app.path.portfolio_images: /uploads/images/portfolio

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    translator: { fallbacks: [ "fr" ] }
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        imagepath : '%app.path.product_images%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

easy_admin:
    entities:
        Post:
            class: MyckiBundle\Entity\Post
            form:
                fields: 
                    - 'title'
                    - 'titleSeo'
                    - { property: 'content', type: 'ckeditor'}
                    - 'published'
                    - 'datePublish'
                    - { property: 'imageFile', type: 'vich_image' }

        Page:
            class: MyckiBundle\Entity\Page
            form:
                fields: ['title', { property: 'content', type: 'ckeditor'}]
        Portfolio:
            class: MyckiBundle\Entity\Portfolio
            form:
                fields: ['title', {property: 'content', type: 'ckeditor'}, 'dateprojet', 'technologies',{property: 'imageFile', type: 'vich_image'}]
        User:
            class: MyckiBundle\Entity\User

    site_name: '<img src="/images/logo.png" /> Mycki Web'
    design:
        menu:
            - { entity: 'Page', icon: 'file' }
            - { entity: 'Post', icon: 'newspaper-o' }
            - { entity: 'Portfolio', icon: 'code' }
            - { entity: 'User', icon: 'user' }
        brand_color: '#56A7DB'

ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar: full


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: MyckiBundle\Entity\User
    from_email:
        address: "stalone12@hotmail.fr"
        sender_name: "stalone12@hotmail.fr"

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false 

vich_uploader:
    db_driver: orm
    mappings:
        product_images:
            uri_prefix:         '%app.path.product_images%'
            upload_destination: '%kernel.root_dir%/../web/uploads/images/blog'
        portfolio_images:
                    uri_prefix:         '%app.path.portfolio_images%'
                    upload_destination: '%kernel.root_dir%/../web/uploads/images/portfolio'