fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /MyckiAdmin

mycki:
    resource: "@MyckiBundle/Resources/config/routing.yml"
    prefix:   /
